package com.OriginHubs.Amraj.entity.enums;

public enum AuditActionType {
    LOGIN,
    PASSWORD_RESET,
    ROLE_CHANGED,
    USER_CREATED,
    USER_DEACTIVATED,
    USER_ACTIVATED,
    HUB_EDIT,
    PRODUCT_UPDATE,
    INVENTORY_TRANSFER,
    ORDER_MODIFICATION,
    ORDER_CREATED,
    ORDER_STATUS_CHANGED,
    TICKET_CREATED,
    TICKET_STATUS_CHANGED,
    TICKET_COMMENT_ADDED,
    SYSTEM_ALERT_CREATED,
    SYSTEM_ALERT_ACKNOWLEDGED
}
